<?php
defined('ABSPATH') || exit;


// Typography sections start

Redux::set_section(
   $opt_name,
   array(
      'title'  => esc_html__('Opening Hours Section', 'restaurant-site'),
      'id'     => 'opening_hours-typography',
      'desc'   => esc_html__('Typography settings', 'restaurant-site'),
      'customizer_width' => '450',
      'subsection' => true,
      'icon'   => 'el el-font',
      'fields' => array(
         array(
            'id'                => 'opening_hours_title-typography',
            'title'  => esc_html__('Title of Opening Hours Section', 'restaurant-site'),
            'type'              => 'typography',
            'google'            => true,
            'font_family_clear' => false,
            'color_alpha'       => true,
            'margin-top'        => true,
            'margin-bottom'     => true,
            'text-transform'     => true,
            'letter-spacing'     => true,
            'word-spacing'     => true,
            'line-height'     => true,
            'text-shadow'       => true,
            'default'           => array(
               'color'       => '#14141d',
               'font-size'   => '',
               'font-family' => '',
               'font-weight' => '',
               'font-style'  => '',
               'line-height' => '',
               'margin-top'    => '',
               'margin-bottom' => '',
               'shadow-color'       => '',
               'shadow-horizontal'  => '0',
               'shadow-vertical'  => '0',
               'shadow-blur'  => '0',
            ),
            'output'            => array('.opening-hours-container__title > h2'),
         ),
         array(
            'id'                => 'opening_hours_subtitle-typography',
            'title'  => esc_html__('Subtitle of Opening Hours Section', 'restaurant-site'),
            'type'              => 'typography',
            'google'            => true,
            'font_family_clear' => false,
            'color_alpha'       => true,
            'margin-top'        => true,
            'margin-bottom'     => true,
            'text-transform'     => true,
            'letter-spacing'     => true,
            'word-spacing'     => true,
            'line-height'     => true,
            'text-shadow'       => true,
            'default'           => array(
               'color'       => '#373844',
               'font-size'   => '',
               'font-family' => '',
               'font-weight' => '',
               'font-style'  => '',
               'line-height' => '',
               'margin-top'    => '',
               'margin-bottom' => '',
               'shadow-color'       => '',
               'shadow-horizontal'  => '0',
               'shadow-vertical'  => '0',
               'shadow-blur'  => '0',
            ),
            'output'            => array('.opening-hours-container__row > p'),
         ),
         array(
            'id'                => 'opening_hours_text-typography',
            'title'  => esc_html__('Text of Opening Hours Section', 'restaurant-site'),
            'type'              => 'typography',
            'google'            => true,
            'font_family_clear' => false,
            'color_alpha'       => true,
            'margin-top'        => true,
            'margin-bottom'     => true,
            'text-transform'     => true,
            'letter-spacing'     => true,
            'word-spacing'     => true,
            'line-height'     => true,
            'text-shadow'       => true,
            'default'           => array(
               'color'       => '#fea100',
               'font-size'   => '',
               'font-family' => '',
               'font-weight' => '',
               'font-style'  => '',
               'line-height' => '',
               'margin-top'    => '',
               'margin-bottom' => '',
               'shadow-color'       => '',
               'shadow-horizontal'  => '0',
               'shadow-vertical'  => '0',
               'shadow-blur'  => '0',
            ),
            'output'            => array('.opening-hours-container__row > p > span'),
         ),
      ),
   )
);
